#%RAML 1.0 DataType


type: array
items:
  type: object
  properties:
      employeeId:
        type: integer
        required: true
      firstNamne:
        type: string
        required: false
      lastNamne: 
        type: string
        required: false
      age:
        type: integer
        required: false
      gender:
        type: string
        required: false
      bloodGroup:
        type: string
        required: false
      email:
        type: string
        required: false
      phoneNumber:
        type: string
        required: false 
      city:
        type: string
        required: false
      role:
        type: string
        required: false
      department:
        type: string
        required: false
      designation:
        type: string
        required: false
      technology:
        type: string
        required: false


  